variables:
  GIT_SUBMODULE_STRATEGY: normal
  POSTGRES_DB: feuerwehrsport-statistik-test
  POSTGRES_USER: feuerwehrsport-statistik
  POSTGRES_PASSWORD: feuerwehrsport-statistik
  POSTGRES_HOST: postgres

default:
  image: lichtbit/ruby:2.5

services:
  - postgres

test:
  stage: test
  script:
  - bundle install --path /cache --without production development
  - RAILS_ENV=test bundle exec rake db:create 
  - DISABLE_SCREENSHOT_OPEN=1 bundle exec rspec spec/features/pages_spec.rb:22

after_script:
  - cat log/test.log