variables:
  GIT_SUBMODULE_STRATEGY: normal
  POSTGRES_DB: feuerwehrsport-statistik-test
  POSTGRES_USER: feuerwehrsport-statistik
  POSTGRES_PASSWORD: feuerwehrsport-statistik
  POSTGRES_HOST: postgres

default:
  image: lichtbit/ruby:2.5

services:
  - postgres

before_script:
  - bundle install --path /cache --without production development

test:rubocop:
  stage: test
  script:
  - bundle exec rubocop --config config/rubocop.yml

test:rspec:
  stage: test
  script:
  - SCREENSHOTS_DISABLED=1 DISABLE_SCREENSHOT_OPEN=1 bundle exec rspec
