default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: feuerwehrsport-statistik
  username: feuerwehrsport-statistik
  password: feuerwehrsport-statistik


development:
  <<: *default

test:
  <<: *default
  database: feuerwehrsport-statistik-test

test_dump:
  <<: *default
  database: feuerwehrsport-statistik-test-dump

production:
  <<: *default
