default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: fws-statistik
  username: fws-statistik
  password: fws-statistik


development:
  <<: *default

test:
  <<: *default
  database: fws-statistik-test

test_dump:
  <<: *default
  database: fws-statistik-test-dump

production:
  <<: *default
