default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: feuerwehrsport-statistik
  username: feuerwehrsport-statistik
  password: feuerwehrsport-statistik

online_default: &online_default
  <<: *default
  database: <%= ENV['RAILS_DB_DATABASE'] %>
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default
  database: feuerwehrsport-statistik-test

production:
  <<: *online_default
