inherit_gem:
  m3_rspec: config/rubocop.yml
inherit_mode:
  merge:
    - Exclude

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6.6
Lint/UnusedMethodArgument:
  Exclude:
  - firesport-series/lib/firesport/series/**/*.rb
Metrics/BlockLength:
  Exclude:
  - '**/*.xlsx.axlsx'
Naming/FileName:
  Exclude:
  - firesport-series/lib/firesport-series.rb
Naming/PredicateName:
  Exclude:
  - app/controllers/backend/backend_controller.rb
Rails/FindEach:
  Exclude:
  - app/models/team.rb
Rails/HelperInstanceVariable:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
  - firesport-series/lib/firesport-series.rb
