inherit_gem:
  m3_rspec: config/rubocop.yml
inherit_mode:
  merge:
    - Exclude

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5.5
Naming/FileName:
  Exclude:
  - firesport-series/lib/firesport-series.rb
Naming/PredicateName:
  Exclude:
  - app/controllers/backend/backend_controller.rb
RSpec/LetSetup:
  Enabled: false
Rails/FindEach:
  Exclude:
  - app/models/team.rb
Rails/LexicallyScopedActionFilter:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
  - firesport-series/lib/firesport-series.rb
