inherit_gem:
  m3_rspec: config/rubocop.yml

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5.3
Naming/FileName:
  Exclude:
  - firesport-series/lib/firesport-series.rb
Naming/PredicateName:
  Exclude:
  - app/controllers/backend/backend_controller.rb
RSpec/LetSetup:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
  - firesport-series/lib/firesport-series.rb
